Homework 4
slavrikk/VyacheslavShapkin pull request #4
Opened 2020-08-15 21:20 UTC by slavrikk

2020-08-18 11:00 UTC, shoggy requested changes
`allure-results` and `.idea` in a repository make me sad

`@FindBy` looks not so good -- please merge in changes after Konstantin approve hw2/3

2020-08-18 11:00 UTC, shoggy commented on .idea/workspace.xml
>    <component name="ChangeListManager">
Remove this file from git index please
```sh
git rm --cached .idea/workspace.xml
```

2020-08-18 11:00 UTC, shoggy commented on pom.xml
> +                    <source>8</source>
The compiler version is configured in `properties` section and here.
Please choose only one, to avoid ambiguities

2020-08-18 11:00 UTC, shoggy commented on pom.xml
>          <dependency>
I think this declaration is redundant because this is plugin and it is already defined in `plugins`

2020-08-18 11:00 UTC, shoggy commented on pom.xml
> +                            </dependency>
What for the plugin has itself in dependencies?

2020-08-18 11:00 UTC, shoggy commented on pom.xml
> +                            <resultsDirectory>${project.build.directory}/allure-results</resultsDirectory>
This property is defined here and in `allure.properties`. Choose one place, please

2020-08-18 19:53 UTC, slavrikk commented on .idea/workspace.xml
>    <component name="ChangeListManager">
done

2020-08-18 19:53 UTC, slavrikk commented on pom.xml
>          <dependency>
done

2020-08-18 19:53 UTC, slavrikk commented on pom.xml
> +                            <resultsDirectory>${project.build.directory}/allure-results</resultsDirectory>
done

2020-08-19 10:56 UTC, slavrikk commented on pom.xml
> +                    <source>8</source>
fix

2020-08-19 10:57 UTC, slavrikk commented on pom.xml
> +                            </dependency>
remove

2020-08-19 15:12 UTC, shoggy approved these changes
Looks good!

Note: job config.xml sent personally

2020-08-25 15:42 UTC, merged