Homework 5
slavrikk/VyacheslavShapkin pull request #5
Opened 2020-08-18 06:01 UTC by slavrikk

2020-08-18 07:02 UTC, DmitryKhodakovsky requested changes
Please resolve comment

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on .idea/misc.xml
> +  <component name="JavaScriptSettings">
Проверь ищет раз `.gitignore`. Не должно быть файлов от IDE

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on .gitignore
> +.idea/workspace.xml
Добавь папку `**/allure-results` в этот файл, чтобы избежать попадания лишних файлов в git

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on pom.xml
> +                                <version>1.9.6</version>
`1.9.6`??? У тебя в `<aspectj.version>1.9.5</aspectj.version>` указана версия `1.9.5`. Будь осторожнее с ними

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on pom.xml
> +                        <artifactId>maven-surefire-plugin</artifactId>
А зачем ты в каждом `profile` переопределяешь `maven-surefire-plugin`?
Можно же имя suite указать как **property** и потом значение передать в основой plugin

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw3/AbstractTest.java
> +package hw3;
Не забудь пожалуйста сделать `rebase` на мастер, когда **hw3** будет заморожена в мастер

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/context/UserTablePage.java
> +    @FindBy(xpath = "//td[3]/a")
Старайся избегать использования индексов в локаторах элементов

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/context/UserTablePage.java
> +    private List<WebElement> checkboxes;
Я бы рекомендовал заменить на `css`

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/context/UserTablePage.java
> +    @FindBy(xpath = "//tr[2]//td[2]/select/option")
Старайся избегать использования индексов в локаторах элементов

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/context/UserTablePage.java
> +    @FindBy(xpath = "//td[1]")
Старайся избегать использования индексов в локаторах элементов

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/context/UserTablePage.java
> +    @FindBy(xpath = "//tr[2]//td[2]//select[1]")
Старайся избегать использования индексов в локаторах элементов

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/RunAcceptanceEx1.java
> +public class RunAcceptanceEx1 extends AbstractTestNGCucumberTests {
`RunAcceptanceEx1`, `RunAcceptanceEx2` и `RunAcceptanceEx3` можно было оставить как 1 класс. Они повторяют друг друга

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/ActionSteps.java
> +        homePage.login("Roman", "Jdi1234");
Лучше имя и пароль в данном случае сделать, как параметры, чтобы не хардкодить значения в коде

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/ActionSteps.java
> +        }
Всю работу с `WebElement` нужно прятать на уровень **PageObjects**. *Step Definitions* не должны ничего знать про WebElements

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/ActionSteps.java
> +    public void i_select_checkbox_for(String string, String string2) {
А зачем тут параметры, если они не используются?

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/ActionSteps.java
> +    @When("I click on {string} button in Header")
Зачем параметр если он не используется?

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void browser_title_should_be_equal(String string) {
Переименуй входные параметры, чтобы было понятнее, что это за параметр, который подаётся на вход в метод

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void name_should_be_displayed_and_equals_to_expected_username(String string) {
Переименуй входные параметры, чтобы было понятнее, что это за параметр, который подаётся на вход в метод

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void page_should_be_opened(String string) {
Переименуй входные параметры, чтобы было понятнее, что это за параметр, который подаётся на вход в метод

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void number_Type_Dropdowns_should_be_displayed_on_Users_Table_on_User_Table_Page(Integer int1) {
Переименуй входные параметры, чтобы было понятнее, что это за параметр, который подаётся на вход в метод

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +        int expectedResult = int1;
Зачем данное преобразование?

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void usernames_should_be_displayed_on_Users_Table_on_User_Table_Page(Integer int1) {
Переименуй входные параметры, чтобы было понятнее, что это за параметр, который подаётся на вход в метод

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +        int expectedResult = int1;
Зачем данное преобразование?

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void description_texts_under_images_should_be_displayed_on_Users_Table_on_User_Table_Page(Integer int1) {
Переименуй входные параметры, чтобы было понятнее, что это за параметр, который подаётся на вход в метод

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +        int expectedResult = int1;
????

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +        int expectedResult = int1;
???

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void checkboxes_should_be_displayed_on_Users_Table_on_User_Table_Page(Integer int1) {
Переименуй входные параметры, чтобы было понятнее, что это за параметр, который подаётся на вход в метод

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void log_row_has_text_in_log_section(Integer int1, String string) {
Переименуй входные параметры, чтобы было понятнее, что это за параметр, который подаётся на вход в метод

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void droplist_should_contain_values_in_column_Type_for_user_Roman(io.cucumber.datatable.DataTable dataTable) {
Переименуй входные параметры, чтобы было понятнее, что это за параметр, который подаётся на вход в метод

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void user_table_should_contain_following_values(io.cucumber.datatable.DataTable dataTable) {
Переименуй входные параметры, чтобы было понятнее, что это за параметр, который подаётся на вход в метод

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/java/hw5/tests/steps/ModelSteps.java
> +    public void i_login_as_user(String string) {
А вот такой шаг уже был) Удалить дубликат

2020-08-18 07:02 UTC, DmitryKhodakovsky commented on src/test/resources/hw5/ex1/ex1.feature
> +    Then Log rows are displayed and dropdown name and selected value is corresponding to selected
Переписать, чтобы соблюдалось условия 
```
GIven
And
...
When 
And
...
Then
And
...
```
Не длолжно быть 
```
Given
Then
When
And
Given
When
When
Than
Than
```

2020-08-19 13:06 UTC, slavrikk commented on .idea/misc.xml
> +  <component name="JavaScriptSettings">
добавил

2020-08-19 13:06 UTC, slavrikk commented on .gitignore
> +.idea/workspace.xml
добавил

2020-08-19 13:06 UTC, slavrikk commented on pom.xml
> +                                <version>1.9.6</version>
исправил

2020-08-19 13:07 UTC, slavrikk commented on pom.xml
> +                        <artifactId>maven-surefire-plugin</artifactId>
исправил для HW5, для HW3 и HW4 исправил в ветке homework_4, так же добавил отдельный профайл на allure

2020-08-19 13:08 UTC, slavrikk commented on src/test/java/hw3/AbstractTest.java
> +package hw3;
помню, HW3 уже в мастере

2020-08-19 13:08 UTC, slavrikk commented on src/test/java/hw5/context/UserTablePage.java
> +    @FindBy(xpath = "//td[3]/a")
исправил

2020-08-19 13:10 UTC, slavrikk commented on src/test/java/hw5/context/UserTablePage.java
> +    private List<WebElement> checkboxes;
заменил на //div[@class..]

2020-08-19 13:11 UTC, slavrikk commented on src/test/java/hw5/context/UserTablePage.java
> +    @FindBy(xpath = "//tr[2]//td[2]/select/option")
убрал 1 индекс

2020-08-19 13:13 UTC, slavrikk commented on src/test/java/hw5/context/UserTablePage.java
> +    @FindBy(xpath = "//td[1]")
для выборки массива строк без индекса не обойтись..

2020-08-19 13:14 UTC, slavrikk commented on src/test/java/hw5/context/UserTablePage.java
> +    @FindBy(xpath = "//tr[2]//td[2]//select[1]")
убрал один индекс

2020-08-19 13:14 UTC, slavrikk commented on src/test/java/hw5/tests/RunAcceptanceEx1.java
> +public class RunAcceptanceEx1 extends AbstractTestNGCucumberTests {
объединил в 1 класс

2020-08-19 13:15 UTC, slavrikk commented on src/test/java/hw5/tests/steps/ActionSteps.java
> +        }
убрал в HomePage

2020-08-19 13:15 UTC, slavrikk commented on src/test/java/hw5/tests/steps/ActionSteps.java
> +    @When("I click on {string} button in Header")
убрал

2020-08-19 13:15 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void name_should_be_displayed_and_equals_to_expected_username(String string) {
изменил

2020-08-19 13:15 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void page_should_be_opened(String string) {
поменял

2020-08-19 13:16 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +        int expectedResult = int1;
перемудрил, сравниваю Integer

2020-08-19 13:16 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void usernames_should_be_displayed_on_Users_Table_on_User_Table_Page(Integer int1) {
изменил

2020-08-19 13:16 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +        int expectedResult = int1;
перемудрил, сравниваю Integer

2020-08-19 13:16 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void description_texts_under_images_should_be_displayed_on_Users_Table_on_User_Table_Page(Integer int1) {
поменял

2020-08-19 13:17 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +        int expectedResult = int1;
перемудрил, сравниваю Integer

2020-08-19 13:17 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +        int expectedResult = int1;
перемудрил, сравниваю Integer

2020-08-19 13:17 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void checkboxes_should_be_displayed_on_Users_Table_on_User_Table_Page(Integer int1) {
изменил

2020-08-19 13:17 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void log_row_has_text_in_log_section(Integer int1, String string) {
изменил

2020-08-19 13:17 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void droplist_should_contain_values_in_column_Type_for_user_Roman(io.cucumber.datatable.DataTable dataTable) {
изменил

2020-08-19 13:17 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void user_table_should_contain_following_values(io.cucumber.datatable.DataTable dataTable) {
поменял

2020-08-19 13:18 UTC, slavrikk commented on src/test/java/hw5/tests/steps/ModelSteps.java
> +    public void i_login_as_user(String string) {
удалил

2020-08-19 13:18 UTC, slavrikk commented on src/test/resources/hw5/ex1/ex1.feature
> +    Then Log rows are displayed and dropdown name and selected value is corresponding to selected
изменил

2020-08-19 13:19 UTC, slavrikk commented on src/test/java/hw5/tests/steps/ActionSteps.java
> +        homePage.login("Roman", "Jdi1234");
добавил в сценарии пароль и логин

2020-08-19 13:19 UTC, slavrikk commented on src/test/java/hw5/tests/steps/ActionSteps.java
> +    public void i_select_checkbox_for(String string, String string2) {
убрал

2020-08-19 13:19 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void browser_title_should_be_equal(String string) {
изменил

2020-08-19 13:19 UTC, slavrikk commented on src/test/java/hw5/tests/steps/AssertionSteps.java
> +    public void number_Type_Dropdowns_should_be_displayed_on_Users_Table_on_User_Table_Page(Integer int1) {
изменил

2020-08-19 21:04 UTC, DmitryKhodakovsky approved these changes
Approved. Could be merged to the master branch

2020-08-19 21:04 UTC, DmitryKhodakovsky commented on src/test/java/hw5/context/UserTablePage.java
> +    @FindBy(xpath = "//td[1]")
В целом можно и без индексов везде обойтись
К примеру в локатор `//tr[2]//select` -> `//tr//select` модно заменить

2020-08-25 15:49 UTC, merged